=== JatinMaharjan/Online-Music-Store/catalog_19032170.dtd
<!ELEMENT Store (header,Details,Song-detail+)>
<!ATTLIST Store 
  xmlns:xs CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  xs:noNamespaceSchemaLocation NMTOKEN #REQUIRED>

<!ELEMENT header (image,Heading)>

<!ELEMENT Details (Storename,Store-Address,Telephone-Number,website)>

<!ELEMENT Song-detail ((Song-Image1?,Song-Image10?,Song-Image11?,Song-Image12?, Song-Image13?,Song-Image14?,Song-Image15?,
Song-Image2?,Song-Image3?,Song-Image4?,Song-Image5?,Song-Image6?,Song-Image7?,Song-Image8?,Song-Image9?),Song-Info)>
<!ATTLIST Song-detail
  SongNo CDATA #REQUIRED>

<!ELEMENT image EMPTY>

<!ELEMENT Heading (#PCDATA)>

<!ELEMENT Storename (#PCDATA)>

<!ELEMENT Store-Address (#PCDATA)>
<!ATTLIST Store-Address
  Main_branch NMTOKEN #REQUIRED>

<!ELEMENT Telephone-Number (#PCDATA)>

<!ELEMENT website (#PCDATA)>

<!ELEMENT Song-Image1 EMPTY>
<!ATTLIST Song-Image1
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image10 EMPTY>
<!ATTLIST Song-Image10
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image11 EMPTY>
<!ATTLIST Song-Image11
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image12 EMPTY>
<!ATTLIST Song-Image12
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image13 EMPTY>
<!ATTLIST Song-Image13
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image14 EMPTY>
<!ATTLIST Song-Image14
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image15 EMPTY>
<!ATTLIST Song-Image15
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image2 EMPTY>
<!ATTLIST Song-Image2
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image3 EMPTY>
<!ATTLIST Song-Image3
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image4 EMPTY>
<!ATTLIST Song-Image4
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image5 EMPTY>
<!ATTLIST Song-Image5
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image6 EMPTY>
<!ATTLIST Song-Image6
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image7 EMPTY>
<!ATTLIST Song-Image7
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image8 EMPTY>
<!ATTLIST Song-Image8
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Image9 EMPTY>
<!ATTLIST Song-Image9
  Image_id CDATA #REQUIRED>

<!ELEMENT Song-Info (description,Song-Name,genre,Director-Name,Co-Director-Name*,Producer_Name,Writer,Band*,Name,Real_Name*,Age,Death-Date*,Sex,Instruments*,
                     Address,Release-Year)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT Song-Name (#PCDATA)>

<!ELEMENT genre (#PCDATA)>
<!ATTLIST genre
  type CDATA #REQUIRED>

<!ELEMENT Director-Name (#PCDATA)>

<!ELEMENT Co-Director-Name (#PCDATA)>

<!ELEMENT Producer_Name (#PCDATA)>

<!ELEMENT Writer (#PCDATA)>

<!ELEMENT Band (#PCDATA)>
<!ATTLIST Band
  members CDATA #REQUIRED>

<!ELEMENT Address (#PCDATA)>

<!ELEMENT Age (#PCDATA)>

<!ELEMENT Death-Date (#PCDATA)>

<!ELEMENT Instruments (#PCDATA)>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT Real_Name (#PCDATA)>

<!ELEMENT Sex (#PCDATA)>

<!ELEMENT Release-Year (#PCDATA)>

=== JatinMaharjan/Online-Music-Store/catalog_19032170.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_19032170.css"?>
<!DOCTYPE Store SYSTEM "catalog_19032170.dtd">

<Store xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="catalog_19032170.xsd">

<header>
    <image/>
    
    <Heading>Blood And Thunder</Heading>
</header>

<Details >
    <Storename>Blood And Thunder</Storename>
    <Store-Address Main_branch="Bhaisepati">Khokana,Lalitpur</Store-Address>
    <Telephone-Number>01-5591345</Telephone-Number>
    <website>www.BloodandThunder.com.np</website>
</Details>

<Song-detail SongNo="01">
    <Song-Image1 Image_id="1"/>
    <Song-Info>
        <description>
            <![CDATA[According to Yorke, "Creep" tells the tale of an inebriated man who tries to get the attention of a woman to whom he is attracted by following her around. This is about being in love with someone, but not feeling good enough. To creep means “to move slowly and carefully, in order to avoid being heard or noticed.]]>
        </description>

        <Song-Name>Song Name: Creep</Song-Name>
        <genre type="Pop">Genre: Pop</genre>
        <Director-Name>Director Name: ‎Paul Q. Kolderie </Director-Name>
        <Producer_Name>Producer Name:  Sean Slade</Producer_Name>
        <Writer>Song Writer: Thom Yorke</Writer>
        <Band members="5">
            Band: Radiohead
        </Band>
            <Name>Singer Name: Thom Yorke</Name>
            <Age>Age: 53</Age>
            <Sex>Sex: Male</Sex>
            <Instruments>Instruments: Vocals, Guitar, Piano</Instruments>
            <Address>Address: Oxfordshire</Address>
        <Release-Year>Song Release Year: 1992</Release-Year>
    </Song-Info>
</Song-detail>

<Song-detail SongNo="02">
    <Song-Image2 Image_id="2"/>
    <Song-Info>
        <description>
            <![CDATA[This song describe about the person who is in love with someone and is just anxious of waiting for the other person. Jeremy Zucker's “comethru” has found a strong audience with 31 million Spotify streams to date. The song is self-produced.]]>
        </description>

        <Song-Name>Song Name: Comethru</Song-Name>
        <genre type="Pop">Genere: Pop indie pop</genre>
        <Director-Name>Director Name: Jeremy Zucker</Director-Name>
        <Producer_Name>Producer Name: Jeremy Zucker</Producer_Name>
        <Writer>Writers Name: Jeremy Zucker</Writer>
        
            <Name>Singer Name: Jeremy Zucker</Name>
            <Age>Age: 25</Age>
            <Sex>Sex: Male</Sex>
            <Address>Address: 2 Soundview cir, White Plains</Address>
       
        <Release-Year>Song Release Year: 2018</Release-Year>
    </Song-Info>
</Song-detail>

<Song-detail SongNo="03">
    <Song-Image3 Image_id="3"/>
    <Song-Info>
        <description>
            <![CDATA[This song is about becoming self-empowered and sawing, 'I'm happy with who I am, happy with the choices I'm making,'" he added. The song is about the realization that the old way of life in which "he" thought he lived is completely destroyed and replaced "ash and dust. ]]>
        </description>

        <Song-Name>Song Name: Radioactive</Song-Name>
        <genre type="Electronic Rock">Genre: Electronic rock alternative rock</genre>
        <Director-Name>Director Name: Lou Diamond Phillips</Director-Name>
        <Producer_Name>Producer Name: Alex da kid</Producer_Name>
        <Writer>Writer: Alex da kid</Writer>
        <Band members="5">
            Band: Imagine Dragons
        </Band>
        
            <Name>Singer Name: Dan Reynolds</Name>
            <Age>Age: 21</Age>
            <Sex>Sex: Male</Sex>
            <Instruments>Instruments: Vocals, GUitar, Piano, Synthesizers</Instruments>
            <Address>Address: Las Vegas</Address>
       
        <Release-Year>Release Year: 2012</Release-Year>
    </Song-Info>
</Song-detail>

<Song-detail SongNo="04">
    <Song-Image4 Image_id="4"/>
    <Song-Info>
        <description>
            <![CDATA["Boneless" is a song by American DJ and producer Steve Aoki in collaboration with European dance music producers Chris Lake and Tujamo. This song defines about the lyric interpretation, video and chart position.]]>
        </description>

        <Song-Name>Song Name: Boneless</Song-Name>
        <genre type="Electro House;hip house">Genere: Electro House;hip house</genre>
        <Director-Name>Director Name: Steve Aoki</Director-Name>
        <Producer_Name>Producer Name: Steve Aoki, Chris Lake, Tujamo</Producer_Name>
        <Writer>Writer: Steve Aoki</Writer>
        
            <Name>Singer Name: Steve Aoki</Name>
            <Age>Age: 30</Age>
            <Sex>Sex: Male</Sex>
            <Address>Address: California</Address>
       
        <Release-Year>Release Year: 2014</Release-Year>
    </Song-Info>
</Song-detail>

<Song-detail SongNo="05">
    <Song-Image5 Image_id="5"/>
    <Song-Info>
        <description>
            <![CDATA["The Nights" is a song by Swedish DJ and record producer Avicii. It is story of how a young man lived an adventurous life and is maybe what  Avicii is trying to say through his lyrics that people should 'Live a life you will remember' because 'One day you will leave this world behind. The nights is an example of a dance/house music song which he is famous for creating, as his is the type of music he produces and is the music he is recognised for all over the world]]>
        </description>

        <Song-Name>Song Name: The Nights</Song-Name>
        <genre type="Progressive house: folktronica">Genre: folktronica</genre>
        <Director-Name>Director Name: Rory Kramer</Director-Name>
        <Producer_Name>Producer Name: Arash Pournouri</Producer_Name>
        <Writer>Writer: Arash Pournouri</Writer>
        
            <Name>Singer Name: Avicii</Name>
            <Real_Name>Real Name: Tim Bergling</Real_Name>
            <Age>Age: 24</Age>
            <Sex>Sex: Male</Sex>
            <Address>Address: Iran</Address>
       
        <Release-Year>Release Year: 2014</Release-Year>
    </Song-Info>
</Song-detail>

<Song-detail SongNo="06">
    <Song-Image6 Image_id="6"/>
    <Song-Info>
        <description>
            <![CDATA["Bohemian Rhapsody" is a song by the British rock band Queen. It was written by Freddie Mercury. The lyrics describe a suicidal murderer haunted by demons or depict events just preceding an execution.]]>
        </description>

        <Song-Name>Song Name: Bohemain Rhapsody</Song-Name>
        <genre type="Profresive rock hard rock">Genere: Profresive rock hard rock</genre>
        <Director-Name>Director Name: Bryan Singer</Director-Name>
        <Co-Director-Name>Co-directory Name: Dexter Fletcher</Co-Director-Name>
        <Producer_Name>Producer Name: Roy Thomas Baker</Producer_Name>
        <Writer>Writer: Freddie Mercury</Writer>
        <Band members="4">
            Band Name: Queen
        </Band>
        
            <Name>Singer Name: Freddie Mercury</Name>
            <Age>Age: 45</Age>
            <Death-Date>Death Date: Nov24, 1991</Death-Date>
            <Sex>Sex: Male</Sex>
            <Address>Address: London</Address>
       
        <Release-Year>Release Year: 1975</Release-Year>
    </Song-Info>
</Song-detail>

<Song-detail SongNo="07">
    <Song-Image7 Image_id="7"/>
    <Song-Info>
        <description>
            <![CDATA[Snow (Hey Oh) is a song by American band Red Hot Chili Peppers from their 2006 double album, Stadium Arcadium. This song is about cocaine and China White heroin, two of lead singer Anthony Kiedis' drugs of choice. Both are a white powdery substance, which looks like snow. The lyrics, "So white as snow... Privately divided by a world so undecided," refer to dividing the coke/heroin into lines, so as to deal them or snort them.]]>
        </description>

        <Song-Name>Song Name: Snow</Song-Name>
        <genre type="Alternative rock">Genre: Alternative rock</genre>
        <Director-Name>Director Name: John Frusciante, Chad Smith</Director-Name>
        <Co-Director-Name>Co-director Name: Anthony Kiedis, Flea</Co-Director-Name>
        <Producer_Name>Producer Name: Anthony Kiedis, John Frusciante, Flea</Producer_Name>
        <Writer>Writer: Flea, Jhon Frusciante, Anthony Kiedis, Chad Smith</Writer>
        <Band members="5">
            Band Name: Red Hot Chilli Pepper
        </Band>
        
            <Name>Singer Name: Anthony Kiedis</Name>
            <Age>Age: 58</Age>
            <Sex>Sex: Male</Sex>
            <Address>Address: America</Address>
       
        <Release-Year>Release Year: 2006</Release-Year>
    </Song-Info>
</Song-detail>

<Song-detail SongNo="08">
    <Song-Image8 Image_id="8"/>
    <Song-Info>
        <description>
            <![CDATA[This song was made and dedicated to Chris Martins mom. She was sick and dieing from a disease that made her skin yellow. The song speaks about love and how devoted he can be towards true love. Naturally people think this song is about liver disease, or even love. I feel this song hit me hard in a different way referring to methamphetamine]]>
        </description>

        <Song-Name>Song Name: Yellow</Song-Name>
        <genre type="Post-Britpop">Genre: Post-Britpop</genre>
        <Director-Name>Director Name: Chris Martin, Will Champion, Jonny Buckland, Guy Berryman</Director-Name>
        <Producer_Name>Producer Name: Ken Nelson</Producer_Name>
        <Writer>Writer: Will Champion, Chris Martin, Guy Berryman, Jonny Buckland</Writer>
        <Band members="5">
            Band Name: Coldplay
        </Band>
        
            <Name>Singer Name: Chris Martin</Name>
            <Age>Age: 44</Age>
            <Sex>Sex: Male</Sex>
            <Address>Address: London</Address>
       
        <Release-Year>Release Year: 2000</Release-Year>
    </Song-Info>
</Song-detail>

<Song-detail SongNo="09">
    <Song-Image9 Image_id="9"/>
    <Song-Info>
        <description>
